[package]
name = "rustyplayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audio-visualizer = "0.3.1"
audiotags = "0.4.1"
claxon = "0.4.3"
clearscreen = "2.0.1"
cpal = "0.15.2"
crossterm = "0.27.0"
dbus = "0.9.7"
device_query = "1.1.3"
indicatif = "0.17.6"
lewton = "0.10.2"
metaflac = "0.2.5"
mpsc = "0.2.0"
rand = "0.8.5"
rdev = "0.5.3"
rodio = "0.17.1"
rustfft = "6.1.0"
souvlaki = "0.6.1"
spectrum-analyzer = "1.4.0"
termion = "2.0.1"
tui = "0.19.0"
walkdir = "2.3.3"
