[package]
name = "rustyplayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audio-visualizer = "0.3.1"
audiotags = "0.4.1"
claxon = "0.4.3"
clearscreen = "2.0.1"
cpal = "0.15.2"
crossterm = "0.27.0"
dbus = "0.9.7"
device_query = "2.0.0"
indicatif = "0.17.6"
lewton = "0.10.2"
metaflac = "0.2.5"
mpsc = "0.2.0"
rand = "0.8.5"
rdev = "0.5.3"
rodio = "0.17.1"
rustfft = "6.1.0"
souvlaki = "0.7.3"
spectrum-analyzer = "1.4.0"
symphonia = "0.5.3"
termion = "3.0.0"
tui = "0.19.0"
walkdir = "2.3.3"
clap = "4.4.18"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
dirs = "5.0.1"
directories = "5.0.1"
anyhow = "1.0.79"
